language: node_js
dist: trusty
node_js:
- '8'
before_install:
- uname -a
- lscpu
- npm install -g npm
- export NODE_ENV=prd;
- git config --global url."https://github.com/".insteadOf ssh://git@github.com/
- git config --global url."https://".insteadOf ssh://
script: gulp build
before_deploy:
- mkdir -p ../dpl_cd_upload
- tar -zcf ../dpl_cd_upload/me.jsx.tar.gz -C ./ .
- git config --local user.name "Travis"
- export TRAVIS_AUTHOR=travis@randytarampi.ca
- export COMMIT_AUTHOR=`git --no-pager show -s --format='%ae' \`git rev-parse\``
- git config --local user.email $TRAVIS_AUTHOR
- shopt -s extglob
- if [[ "$TRAVIS_COMMIT_MESSAGE" =~ !(^0.0.0-[0-9]{10}$) ]]; then npm version "0.0.0-`date -u
  +%s`"; fi;
deploy:
  provider: releases
  api_key:
    secure: 2Gh10Gi1NqXqnVrpAldZjAs5/LUA+PDyy71c+nahH3lXLrzuGjr6kiwkpdOIyMn7Vm9foVtyKTh63TP5CQINffynaXjZTr2ERXaEPDQ7Bk3j/EAu9R89Z8DDKJ/KI+MjQ2zc4b/sZU7iAZEEc3MT3JCllSL0QIRnMjv/EwdJAdS9KxFuplrpETeVhB9njpkIWpFlDdAXD6AWENwDJPs2vsREirPMwVI2uotT1Pdpv8wv+QrphL73jkz+pUgHhGOtN87oCPSjFICkGwLIJ6KqAyTVtOMtXf09ZrS5myLJz/SWM0JwxuxjBRjHdp1zGVD9IFZwAgsuGD/bJ5aYWr8iymAvrMGGkt+rltzh6PxTjIq8puwRIrbB8zayiLZDYlmQpCEboZnVqhAzeHte+ax0QcaJuAjrM5PMyiRXpkaTzesCpB/n4+9Zdetm2pUWudaSER+0sbAHUehnoHLt6X6RnI3UMlrBnPFk2M3lQP0j9P+cuWSUDU2qCkTvulGEGbI9LQ01Q3AWptEBsn5kkaR0ikOV78uFEPuRx4N/Z2GIMXZbI0+9IP0NhhBUETu58raxaTSQ59qHEg5qw3YQDQ1PDD0OzE1BlTb+QrlP22oBv7UyFM0QepznLvaddBJybIQGomOyXkhOSXQDeN/uWnI4ezyU4IW+njFipj5jEG33TQU=
  file: me.jsx.tar.gz
  skip_cleanup: true
  on:
    branch: master
    node: 8
after_deploy:
- git push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG} HEAD:master;
notifications:
  slack:
    secure: p/NT1Ms/u55XCNS4fwnN7uDXzvFaWZNMr1IItTyilVzNxRC/+8MyKz1lGtulqHjQu9MsYrfKBzvSfruhfpEPEziWhL6q8KrG+MW6iojyyXSKvPBFOzV+aKLSu8RZ675qpbH2p+krLHVtrDoOT92tsy2zqCEkdr2k0Z9j7QpQoa5jVlNzKgsPV33ME7FcLa9aGXblIAEF09ZpHizYjWWSL84WUvwMDELkZCsv56IuspZ3BX5JPR9kW66jidle8YdN/cJjI0WQmQcYCara4B7wjAKLfktlwX3PxASri4V+i88AP2g5PPv+HNrALMXrexTlzLuB6MlijVNtxOOZiz6FszUJnlnRWgln/obtEw3Wogyt0Z9putRODIBIel37PEHii4J0ZMfmiPF67er5T0CLfbFrzwZWmt5x2vAPgpdmgEkYnADJW9Myc8nZbxLgA1Y7lF99HY/ksvOZwzQhl1uy6cm859LqEZUZI7DcLSzhEgO2y4uH7xOBgnDAuyiABASAc0YZrw3gUD39jYiabzz2Z9n3BsgnWpBf/GrqVCvYIqkMJqNZm0zH6uDk0u7erxyB3lqGBoOiMdLEimx5G2O4O0wRmmfEteCQG1dqc+mAwPkatNGfqc0hO3Zvzn4eFjwy4fFyE9gdVVRf9JcqAFnN3PC4GR1Lc29I+H99fXkbvgM=
